### ISSUE TITLE
tle update

### ISSUE THREAD

**Issue by rasoulmy** [cbassa/strf#1]
Hi 
At first I Thank you for your Excellent satellite tracking software. I want to use these codes in my research project. After working on your code about one month , I  could n't find the function that update's   TLE , Please help me  about that
​

Best Regards

**Comment by cbassa** [comment]
A script to download TLE's is part of sattools: https://github.com/cbassa/sattools/blob/master/scripts/stget.sh

**Comment by rasoulmy** [comment]
?Hello again

Thank you a lot  Mr Cbassa. but I have a problem in run this file. I use wcslib version 4.24-1 and I can not utilize and make functions. If it is possible , please  run codes with this version of wcslib. This is very vital in my educational progress. Certainly I do not forget your kindness.

Best regards.


________________________________

**Comment by cbassa** [comment]
Indeed, sattools/strf uses an older wcslib version. You can get it from here: http://www.epta.eu.org/%7Ebassa/wcslib-2.9.tar

**Comment by rasoulmy** [comment]
Thanks a lot mr cbassa, this file will help me. I am sorry, in file rv2tle, what is input file format(xyzfile)?I havent any example  or data for this

Best Regards

________________________________
