### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by hasan1371** [cbassa/strf#28]
Hi, i have segfault problem with rmse limit in strf. when I want to enter rmse limit it showed me core dumped error.
can you help me solve this error?
thanks

**Comment by kerel-fs** [comment]
Please provide more information so that we can understand the problem.

1. The state of the environment variables
   ```bash
   echo -e "env variables:\n$ST_DATADIR\n$ST_TLEDIR\n$ST_COSPAR"
   ```
2. Which commands did you run?
3. Which data files, tle files & sites.txt did you use?

**Comment by microp11** [comment]
Hi, I am running into the following error using the master branch as of today Nov 15, 2022 22:07 AST.

I have been following step by step the tutorials at: https://destevez.net/2019/01/an-strf-crash-course/ using the original 15G recording kindly provided by Daniel today.

The problem occurs at "ex6: identifying an unknown sat". After pressing "i" to identify the signal based on Doppler, I introduce 0.1 as rms limit and press enter:
```
paul@Latitude-E6540:~/repos/strf/data$ rffit -d out.dat
2014-01-01T00:00:00_435.654_0000_-0001.dat
Save highlighted points, provide filename: ex6-before-i-unknown.dat
38 points saved in ex6-before-i-unknown.dat

================================================================================
rms limit (kHz): 0.1
Segmentation fault (core dumped)
paul@Latitude-E6540:~/repos/strf/data$ 

```

![image](https://user-images.githubusercontent.com/1545798/202066766-be025f1e-5cfe-4a33-a8d6-1f6025624568.png)

I have rebooted the system and tried different values for rms.

Up to this crash I have followed the tutorials step by step without problems.
I can provide any other info that is needed, or willing to try any suggestion. Thanks.

```
paul@Latitude-E6540:~/repos/strf/data$ echo -e "env variables:\n$ST_DATADIR\n$ST_TLEDIR\n$ST_COSPAR"
env variables:
/home/paul/repos/strf
/home/paul/tle
0000

```

**Comment by microp11** [comment]
Just wanted to add, the TLEs are the ones provided by the tutorial: https://gist.github.com/daniestevez/b69ffae338fcaf5d5588c03995adb508

**Comment by microp11** [comment]
Same problem with an older version of Ubuntu:
```
paul@paul-Aspire-1410:~/repos/strf/data$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
paul@paul-Aspire-1410:~/repos/strf/data$ 
```
I will try using some older commits. Hopefully one will work. Or move to other IQ, recent ones for tryouts.

**Comment by microp11** [comment]
Went down and made a couple of builds down to 0177a2d38f3d88408bc2961c53cf4e41002b5238 April 8 2021 commit. Same error.

**Comment by cbassa** [comment]
This error appears to be caused because you have no TLEs loaded. Will try to fix.
