### ISSUE TITLE
Adalm Pluto part needs "update" 

### ISSUE THREAD

**Issue by zanco** [cbassa/strf#29]
Trying to get the Pluto to write the data threw errors over here, as "unable to set antenna port" and "unable to set gain"

Some googling around the Pluto Wiki and the q&a's on the website pointed to a topic where the note said that from version 0.23 you needed to specify either -i (for input) or -o for some settings. After trying a few I ended up with this working solution.

`iio_attr -u usb:1.4.5 -c ad9361-phy RX_LO frequency 436500000
iio_attr -u usb:1.4.5 -i -c ad9361-phy voltage0 rf_port_select A_BALANCED
iio_attr -u usb:1.4.5 -i -c ad9361-phy voltage0 rf_bandwidth 2000000
iio_attr -u usb:1.4.5 -i -c ad9361-phy voltage0 sampling_frequency 2000000
iio_attr -u usb:1.4.5 -i -c ad9361-phy voltage0 gain_control_mode manual
iio_attr -u usb:1.4.5 -i -c ad9361-phy voltage0 hardwaregain 32
iio_readdev -u usb:1.4.5 cf-ad9361-lpc -b 4194304  | ./rffft -f 436500000 -s 2000000 -F int`

After a restart of the Ubuntu 20.04 I noticed the 1.4.5 moved to 1.2.5

Now I replaced all instances of usb:1.4.5 by ip:192.168.2.1 which appears to run ok now.

**Comment by cbassa** [comment]
Hi Ben. From what I can tell, this isn't an issue with STRF, but more with the Pluto software. I'll close this for now.
