### ISSUE TITLE
versafit 

### ISSUE THREAD

**Issue by RobertSmith1990** [cbassa/strf#31]
Hi
I read rffit.c , versafit.c and understood that it uses versafit to modify tle parameters such as inclination, mean motion. Does anyone know how versafit estimates these parameters?

**Comment by cbassa** [comment]
versafit doesn't estimate these parameters, instead from rffit you provide estimates which versafit then tries to improve. Once you've loaded a Doppler curve, you can use the `t` key to toggle between different orbit estimates to start fitting from.

**Comment by RobertSmith1990** [comment]
Thanks for the reply
After selecting the parameter and pressing the f button
   How does versafit improve tle parameters?
What mathematical relationship does he use to do this?
I want to know if it is possible to achieve better results by using genetic algorithm (for example)?

**Comment by cbassa** [comment]
Good questions!

Versafit is an implementation of the Nelder & Mead downhill simplex method and it uses the chi-squared function that it tries to minimize. This is the quadratic sum of the residuals, so the observed frequencies minus the predicted frequencies.
The predicted frequencies use the SGP4 orbital model to compute line-of-sight velocities to the observer, which requires the 7 orbital parameters (mean anomaly, RA of the ascending node, inclination, mean motion, eccentricity, argument of perigee and B* drag).

It should definitely be possible to achieve better results, or at least understand the correlations between the different parameters. I have some python code that uses MCMC to improve upon orbital estimates. 

For rffit I chose to use the downhill simplex method as it is very easy to enable/disable fitting for certain parameters, which greatly helps in the manual operation of fitting an orbit from scratch.

**Comment by muhammadali1377** [comment]
> can you tell me how predicted frequencies use the SGP4 orbital model to compute line-of-sight velocities to the observer?
