### ISSUE TITLE
/usr/local/bin/tleupdate: line 51: /data/desig.txt: No such file or directory

### ISSUE THREAD

**Issue by kittybwained** [cbassa/strf#34]
Hello! I was trying to set up strf, and the guide told me to run tleupdate i got this error:

dos2unix: converting file kepler.tle to Unix format...
cat: catalog.tle: No such file or directory
/usr/local/bin/tleupdate: line 51: /data/desig.txt: No such file or directory

What i added to my .bashrc and .zshrc files: 
ST_DATADIR=$HOME/src/strf
ST_TLEDIR=$HOME/tle
ST_COSPAR=$ST_DATADIR/data/sites.txt
and obviously the login one, but i'm not showing that

I also get a bunch of .txt and .tle files appear in my home directory whenever i run this command.
I didn't have a tle directory before, so i created an empty one, is that an issue?
Full log at: https://rentry.co/k4ytq
Any help would be appreciated!

**Comment by cbassa** [comment]
It looks like catalog.tle is absent which results in the other errors. Can you check by running the wget commands from spacetrack.org manually?

**Comment by kittybwained** [comment]
Yes, i get this:
```
--2023-01-07 20:35:19--  https://www.space-track.org/basicspacedata/query/class/tle_latest/ORDINAL/1/EPOCH/%3Enow-30/format/3le
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving www.space-track.org (www.space-track.org)... 35.215.103.41, 64:ff9b::23d7:6729
Connecting to www.space-track.org (www.space-track.org)|35.215.103.41|:443... connected.
HTTP request sent, awaiting response... 204 No Content
2023-01-07 20:35:19 (0.00 B/s) - ‘catalog.tle’ saved [0]

```

**Comment by kittybwained** [comment]
I have switched distros (for unrelated reasons) but it's still the same issue
if i go to that url in my web browser i can see it just fine, so maybe it's an authentication issue?

**Comment by kittybwained** [comment]
Oh wow, i just realised that i hadn't actually ran ```source .bashrc```, but even after i run it and i do have the $ST_LOGIN variable it's still the same issue!

**Comment by kittybwained** [comment]
To me it seems like maybe the first command fails? When i run tleupdate i don't see it actually trying to get catalog.tle

**Comment by cbassa** [comment]
Can you confirm that you have an account at space-track.org and that this is correctly set in ST_LOGIN?

**Comment by kittybwained** [comment]
Yes, a simple python script does give me a response code of 200, also removing the if statement from the tleupdate script seems to have fixed the catalog.tle issue but it still can't find /data/desig.txt

**Comment by cbassa** [comment]
Do you have $ST_DATADIR set as well?

**Comment by kittybwained** [comment]
yes, $ST_DATADIR is equal to /home/glados/src/strf
replacing $ST_DATADIR in the script with the string /home/glados/src/strf results in no errors now

**Comment by kittybwained** [comment]
maybe because that variable contains the $HOME variable in it?

**Comment by cbassa** [comment]
Can you post the full log of a tleupdate run?

**Comment by kittybwained** [comment]
It also spammed my home directory with .tle and .txt files so i changed the variable to the string of /home/glados/tle and removed the if statement with the mkdir command, my guess is that for some reason my bash doesn't like these variables?
Anyway, here's the log: https://rentry.co/dfzo3

**Comment by cbassa** [comment]
From what I can tell from that log file `tleupdate` works as expected

**Comment by kittybwained** [comment]
Actually,  i think i fixed it, changing the .bashrc lines from just ST_DATADIR=[...] to export ST_DATADIR=[...], seems to have fixed it, even with a stock tleupdate

**Comment by kittybwained** [comment]
Yes, thank you for your help
> From what I can tell from that log file `tleupdate` works as expected
