### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cbassa/strf#4]
I would like to point out that an identifier like "[`_SATUTL_H`](https://github.com/cbassa/strf/blob/aedfe3ed0e5e3c1f9453aea2a250d19b646683d0/satutl.h#L5 "Update candidate")" [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by cbassa** [comment]
Your comments are very valid, but go outside of the scope for this software. I prefer to spend my programming time to implement useful features, not to spend time learning coding standards.

**Comment by elfring** [comment]
Can safe signal processing fit better together with secure programming conventions?

**Comment by cbassa** [comment]
Probably, but not at the cost of my free time to spend on my hobby.

**Comment by elfring** [comment]
How much does [ASTRON](https://www.astron.nl/ "Netherlands Institute for Radio Astronomy") (and related researchers) depend on this software?

**Comment by elfring** [comment]
Why did you dare to delete constructive questions?

**Comment by cbassa** [comment]
Because they go beyond the scope of this project.

**Comment by elfring** [comment]
I find this kind of response inappropriate.

**Comment by cbassa** [comment]
That is your problem. Not mine.

**Comment by elfring** [comment]
Would you like to clarify the “project scope” by any other communication means?

**Comment by cbassa** [comment]
Since I'm not a computer scientist I prefer to spend my limited amount of free time programming by implementing useful features instead of adhering to coding standards.

**Comment by elfring** [comment]
* Can [you](https://www.astron.nl/astronomy-group/people/people "ASTRON staff") work better together with any other software developers?
* How do you think about the application of known standards to determine meaningful astronomy data?

**Comment by cbassa** [comment]
This is getting funny. First off, this is a hobby project, not professional, and even without adhering to standards, the data is still very meaningful. Anyway, it feels like I'm feeding a troll, so thanks for your suggestions, but let's end this discussion here.
