### ISSUE TITLE
Problem with large number of bins when passing 00 UTC

### ISSUE THREAD

**Issue by zanco** [cbassa/strf#49]
have this recording with 1463 bin files

I run plot for the specific frequency range with : 

rfplot -p 2023-05-01T11:33:41 -z 0.0006 -s 360 -l 72000 -f 436025000 -w 170000

2023-05-01T11:33:41_001464.bin does not exist
Read spectrogram
1700 channels, 72000 subints
Frequency: 436.025 MHz
Bandwidth: 0.17 MHz
Loaded 7503 orbits
Traces for 52 objects for location 2671

So, my recording / logging started on the 1st of may around 11:33 UTC.

This is the plot result, because starting from s 360 the start time is just before 18:00 UTC

![plot example](https://user-images.githubusercontent.com/4477734/236137772-64ebbb2c-4045-4f14-bdb8-205d5a463b92.png)

I walk through the plot with backspace

That shows at a certain moment this output:

![plot zoomed](https://user-images.githubusercontent.com/4477734/236137933-7f93bbb3-3db2-4165-98ec-1276b8ef5b19.png)

Which has to be from 2023-05-02 unknown satellite starting  at 11:12 UTC 

So, running s and f exits in segmentation fault

But if I plot the same file starting at -s 1320

![plot partly](https://user-images.githubusercontent.com/4477734/236138112-42df3af7-1d81-408d-b82a-5928f21111ae.png)

The UT Date at the bottom is 2023-05-02 

s and f does not terminate in an segmentation fault

![match plot](https://user-images.githubusercontent.com/4477734/236138320-fe89eed4-31cc-4807-b875-c85bbf327b2e.png)

Astrocast-0105 ,  no segmentation fault

So, the big question is, should the plot switch to the new date if you pass the 00 UTC timestamp when "tabbing" throug and observation, and if yes, would that solve the segmentation fault I ran into and got solved by only plotting a smaller part of the strf obs ?

Thanks
Ben

**Comment by cbassa** [comment]
Indeed, when panning through the waterfall, the x-axis label doesn't update when you cross into a later date. This is a minor issue which I'll think about if it needs fixing. As for the segmentation fault, I do not think this is related to this date issue, so may be something else. That's impossible for me to check without the same data.
