### ISSUE TITLE
UT date on bottom of rfplot output does not go to next day after passing 00:00 (UTC)

### ISSUE THREAD

**Issue by zanco** [cbassa/strf#55]
Hi,
if I did run rfplot and found a new satellite I do a run on an (very) large amount of bins but filtered for the identified frequency and bandwidth.  my -l can be like 72000 just to check if my identification matches on next passes.

However, the UT date does not go up if I have tabbed through a day of strf. 

For exameple, with -s 3160 and -l 72000 I find my id's satellite on the 2024-01-17  09:40

![image](https://github.com/cbassa/strf/assets/4477734/1b192ea4-76a6-404c-9b62-58ab25fab5b0)

But if I start at -s 2760 , which is at 2024-01-16, I find the same next pass on the 09:40 UTC time from above, except the UT date on the bottom is 2024-01-16

![image](https://github.com/cbassa/strf/assets/4477734/ec9c9792-6152-48f0-a21c-bea1a816ca47)

So, if possible, update the date after passing midnight :-)

Thanks

**Comment by xmichaelx** [comment]
@cbassa perhaps this can be fixed that instead of  passing `s.nfd0` here  https://github.com/cbassa/strf/blob/0df9fefbc5c9ed8b9b2f332cee764a5aa02fde46/rfplot.c#L282 we could compute it from https://github.com/cbassa/strf/blob/0df9fefbc5c9ed8b9b2f332cee764a5aa02fde46/rfplot.c#L261 and pass date string for `xmin` ?

**Comment by cbassa** [comment]
It might actually be as simple as getting the date string for `s.mjd[xmin]` as I think `xmin` is the starting index of the spectrogram.

**Comment by xmichaelx** [comment]
I had to add it cause xmin was having negative values, hence thresholding it at zero.
