### ISSUE TITLE
cpgplot.h not found when doing make

### ISSUE THREAD

**Issue by RCCRAFT1** [cbassa/strf#58]
<img width="579" alt="Screenshot 2024-10-18 at 10 41 05 AM" src="https://github.com/user-attachments/assets/c2191ac1-006a-4e78-95e7-1f5f6374e119">

Hello,

Upon running the "make" command required to install the commands, I get the error that a certain file is missing. Removing, updating, and reinstalling my dependencies within apt do not fix the issue. I also cannot seem to find this file anywhere else so I am wondering if this is necessary.

**Comment by cbassa** [comment]
This would suggest that pgplot is not properly installed. Is it part of your dependencies?

**Comment by RCCRAFT1** [comment]
Well, upon running `sudo apt install pgplot5` (as mentioned in the readme) it seems to install fine, however its just this one file that cant be found. is there perhaps something i am missing? is there a version of pgplot that i am supposed to be using?

**Comment by RCCRAFT1** [comment]
Upon further investigation, I found that installing "libpgplot" (or similar, dont remember) fixed the issues.

**Comment by MartinHerren** [comment]
For other hitting this issue.

You might have used a recent Debian / Ubuntu based system.

The `pgplot5` package has (finally and correctly) been split into a `libpgplot5` and a `pgplot5-dev` package.

Installing `pgplot5` is equivalent of installing `libpgplot5` which is only the runtime. To compile STRF you need to install `pgplot5-dev`.

I'll open a PR updating the README.
