### ISSUE TITLE
tobs_determining

### ISSUE THREAD

**Issue by rasoulmy** [cbassa/strf#8]
Thanks, but I search for optimum t_obs for any data, how we can reach to this goal?
As you know, this value differ for each data.

**Comment by cbassa** [comment]
The -t option in rffft sets the time length of each spectrum. So with 100Hz frequency resolution you get 100 spectra per second, so with -t 1.0 [the default], you average 100 spectra. The optimum integration length will depend on what you are trying to see. For normal Doppler curves, 1s integrations are fine, but if you want to see Doppler from rotation then you may need shorter integration times.

**Comment by rasoulmy** [comment]
thanks a lot,but i have similar problem in rffind function,what is the criterion for choice otimum S(sigma)?
